services:
  trello-backup:
    build: .
    container_name: trello-backup
    volumes:
      - /backups/trello/:/backups/
    environment:
      - INSTANT_RUN=true
      - CRON=* * * * *
      - TRELLO_KEY=${TRELLO_KEY}
      - TRELLO_TOKEN=${TRELLO_TOKEN}
